### PR TITLE
Added loading spinner and some CSS

### PR DESCRIPTION
**Pull request by Adittya-Gupta**
I have added a loader which shows up while the javascript is fetching the data from the api
Also I have added some css to the result page to make it more appealing

### CODE REVIEW

**Comment by Adittya-Gupta** [comment]
I made this PR in the context of HactoberFest 2022

**Comment by codemaniac-sahil** [comment]
Screenshot (30)
@Adittya-Gupta  check the alignment of example and audio

**Comment by codemaniac-sahil** [comment]
apart from this everything is awesome

**Comment by codemaniac-sahil** [comment]
plus if you change the font-family of the text then it will be great.

**Comment by Adittya-Gupta** [comment]
@codemaniac-sahil made the necessary changes as suggested by you

**Comment by codemaniac-sahil** [comment]
excellent work @Adittya-Gupta

**Pull request merged**
