### PR TITLE
Changed Background and Styled it with Animation

### PR DESCRIPTION
**Pull request by RishitaGangwal**
Animated background looks more attractive!

### CODE REVIEW

**Comment by codemaniac-sahil** [comment]
You styling is not visible
Screenshot from 2022-10-04 18-45-13

**Comment by codemaniac-sahil** [comment]
i think you did not upload bg5.jpg file

**Comment by RishitaGangwal** [comment]
Its included and on my laptop its working properly.

**Comment by codemaniac-sahil** [comment]
Screenshot (39)
but it is not showing here

**Comment by RishitaGangwal** [comment]
Oh no, why this issue is coming?

**Comment by codemaniac-sahil** [comment]
Screenshot (40)
See here you only upload 1 file

**Comment by RishitaGangwal** [comment]
bgimg

See, its visible here but not on your screen, why?

**Comment by RishitaGangwal** [comment]
Now what should I do?
Can you please guide me?

**Comment by codemaniac-sahil** [comment]
let's discuss this in discord

**Comment by RishitaGangwal** [comment]
Sure.

**Pull request closed without merging**
