### PR TITLE
Improvement in UI and Footer #51

### PR DESCRIPTION
**Pull request by anushkamandal25**

### CODE REVIEW

**Comment by anushkamandal25** [comment]
@codemaniac-sahil Hello!! Can you please help me out with the branch conflict that its showing. I cant figure it out. And please check my pr

**Comment by anushkamandal25** [comment]
@codemaniac-sahil please check my pr

**Comment by codemaniac-sahil** [comment]
okay @anushkamandal25 Let me review your PR and try to resolve the conflicts

**Comment by codemaniac-sahil** [comment]
@anushkamandal25 do one thing fork this repository again and then made your changes.

**Comment by anushkamandal25** [comment]
@codemaniac-sahil Is the issue resolved ? Or do I need to fork again?

**Comment by codemaniac-sahil** [comment]
yes, It is resolved

**Pull request merged**
